version: '3.4'

services:
  fletchling.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
    ports:
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  fletchling.web:
    build:
        target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./fletchling.web:/app
      - /app/node_modules
      - /app/.next