version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
    env_file:
      - ./Api/Fletchling.Api/.env
    ports:
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  web:
    build:
        target: dev
    environment:
      - NODE_ENV=development
    env_file:
      - ./Web/fletchling.web/.env
    ports:
      - "3000:3000"
    volumes:
      - ./Web/fletchling.web:/app
      - /app/node_modules
      - /app/.next